### ISSUE TITLE
Bookmark radio buttons are weird

### ISSUE THREAD

**Issue by Andr0id16** [DateMasamune2000/aws_startpage#2]
### Description

Bookmarks card with radio buttons behaves weirdly
1. Clicking a radio button redirects me to the bookmark, _however_ returning to the app, causes the radio button to stay selected. 
2. Deleting a selected bookmark causes the next bookmark to get selected.

### Steps to reproduce:
1.
   1.  Click on a bookmark radio button
   2.  Return to app from redirected page
 
2.
   1. Select a radio button
   2. Delete selected radio button

### Suggested Changes
 
Since a Bookmarks card consists of a list of hyperlinks, radio buttons are out of place. Embedding the hyperlink into the text and getting rid of the radio buttons seems like a good idea.

**Comment by varun872** [comment]
Fixed the issue
Thanks for the suggestions
